export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
export const INVALID_DATA = 'INVALID_DATA';
export const DUPLICATE_NAME = 'DUPLICATE_NAME';
export const USERNAME_DUPLICATE = 'USERNAME_DUPLICATE';
export const EMAIL_DUPLICATE = 'EMAIL_DUPLICATE';
export const RESOURCE_DUPLICATE = 'RESOURCE_DUPLICATE';

module.exports = {
    RESOURCE_NOT_FOUND,
    INVALID_DATA,
    USERNAME_DUPLICATE,
    EMAIL_DUPLICATE,
    RESOURCE_DUPLICATE,
};