const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
const INVALID_DATA = 'INVALID_DATA';
const DUPLICATE_NAME = 'DUPLICATE_NAME';
const USERNAME_DUPLICATE = 'USERNAME_DUPLICATE';
const EMAIL_DUPLICATE = 'EMAIL_DUPLICATE';
const RESOURCE_DUPLICATE = 'RESOURCE_DUPLICATE';

module.exports = {
  RESOURCE_NOT_FOUND,
  INVALID_DATA,
  DUPLICATE_NAME,
  USERNAME_DUPLICATE,
  EMAIL_DUPLICATE,
  RESOURCE_DUPLICATE,
};
